CREATE TABLE IF NOT EXISTS users (
    chat_id BIGINT PRIMARY KEY,
    username VARCHAR,
    first_name VARCHAR,
    last_name VARCHAR,
    bot_state VARCHAR
);

CREATE TABLE IF NOT EXISTS time_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slot_date DATE,
    slot_time TIME,
    chat_id BIGINT
);

CREATE TABLE IF NOT EXISTS applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT,
    address VARCHAR,
    type_application VARCHAR,
    time_slot_id BIGINT,
    FOREIGN KEY (time_slot_id) REFERENCES time_slots(id)
);